### ISSUE TITLE
Where to put UID?

### ISSUE THREAD

**Issue by Eriotouwa** [IPFR33LY/EverwingHax#2]
I followed the README and I don't know where to put my UID, everytime I open Everwing_data.py, there are no screen prompts and just says "invalid syntax" and shuts down. I don't know anything about programming so sorry for asking this question. My UID is 1433010576793975 if its needed. Thanks!

**Comment by IPFR33LY** [comment]
You'll need to copy the entire error that pops up before I can try to help you.

I am, however, in the process of making a website that will do what this script does.

`Open CMD prompt, navigate in CMD to where you placed both everwing_data.py and P3lzstring.py. then type python Everwing_data.py

It shouldn't close the window automatically, if there are errors. They will be displayed.`

**Comment by IPFR33LY** [comment]
I released an executable for the python script. You can find it here.

https://github.com/IPFR33LY/EverwingHax/releases/tag/v1.0
