### ISSUE TITLE
Everwing_data closes when I run it.

### ISSUE THREAD

**Issue by narutoichigoroxas24** [IPFR33LY/EverwingHax#3]
is it just my computer? everytime I ran Everwing_data it closes by itself. no prompts were displayed after closing.

**Comment by IPFR33LY** [comment]
Open CMD prompt, navigate in CMD to where you placed both everwing_data.py and P3lzstring.py. then type python Everwing_data.py

It shouldn't close the window automatically, if there are errors. They will be displayed.

**Comment by narutoichigoroxas24** [comment]
It still doesn't work. I have python 2 installed

EDIT:
  File "Everwing_data.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by IPFR33LY** [comment]
Once I get to a computer. I can help you better. So about 1hr.

**Comment by IPFR33LY** [comment]
I released an executable for the python script. You can find it here.

https://github.com/IPFR33LY/EverwingHax/releases/tag/v1.0
