### ISSUE TITLE
Cant get my uid

### ISSUE THREAD

**Issue by Larsy93** [IPFR33LY/EverwingHax#5]
Cant get my uid

**Comment by IPFR33LY** [comment]
If using chrome, you need to hit F12 to pull up the developer console. Then click on the network tab, now load up everwing and let it load all the way.

go back to the network tab in the developer console. In the filter field, enter in
 `https://wintermute-151001.appspot.com/game/session/everwing/`

Your UID (user ID) should be the numbers on the end.
